
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvuwfbpdasoabrwnesxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2dXdmYnBkYXNvYWJyd25lc3h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NjI3MjUsImV4cCI6MjA2NTQzODcyNX0.eC5A1OcFUckgfU4yom1jTjeVDmi-2JXuxOpfCvK46PM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
